/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab02NetBeans;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("Hello World");
    }
}
